defaults:
  - data: dorsal        # mmcbnu
  - model: resnet50
  - loss: triplet_batchhard
  - train: default 
  - eval: default
  - index: faiss_cpu # uv run python .\src\index\build_index.py data=dorsal eval.ckpt=last index.split=train
  - transforms: medium